from __future__ import annotations

import hashlib
import json
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from am_print_executor.audited_artifact_upload_v33 import (
    Gate3V33Error,
    expected_authorization_phrase,
    UploadResult,
    run_gate3_v33,
    upload_audited_artifact,
)


class FakeFTP:
    def __init__(self, *args, files=None, **kwargs):
        self.files = files if files is not None else {}
        self.cwd_value = None
        self.connected = False

    def connect(self, host, port, timeout=None): self.connected = True
    def login(self, user, password): return "230"
    def prot_p(self): return "200"
    def cwd(self, path): self.cwd_value = path
    def size(self, name):
        if name not in self.files:
            raise RuntimeError("550 not found")
        return len(self.files[name])
    def storbinary(self, cmd, handle):
        name = cmd.split(" ", 1)[1]
        self.files[name] = handle.read()
    def retrbinary(self, cmd, callback):
        name = cmd.split(" ", 1)[1]
        if name not in self.files:
            raise RuntimeError("550 not found")
        data = self.files[name]
        for start in range(0, len(data), 7):
            callback(data[start:start+7])
    def delete(self, name): self.files.pop(name, None)
    def quit(self): pass
    def close(self): pass


class Gate3Tests(unittest.TestCase):
    def make_artifact(self, root: Path) -> tuple[Path, str]:
        path = root / "controlled_slice_smoke.gcode.3mf"
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("Metadata/plate_1.gcode", "; generated by Bambu Studio\nG1 X1 Y1\n")
            archive.writestr("3D/3dmodel.model", "model")
        sha = hashlib.sha256(path.read_bytes()).hexdigest()
        return path, sha

    def test_authorization_phrase_is_request_bound(self):
        self.assertEqual(
            expected_authorization_phrase("M2-1E4B2301FADD"),
            "UPLOAD_AUDITED_M2-1E4B2301FADD",
        )

    def test_new_artifact_upload_is_retained_and_verified(self):
        with tempfile.TemporaryDirectory() as tmp:
            artifact, sha = self.make_artifact(Path(tmp))
            shared = {}
            factory = lambda **kwargs: FakeFTP(files=shared)
            result = upload_audited_artifact(
                ip_address="192.168.1.5",
                access_code="secret",
                artifact_path=artifact,
                artifact_sha256=sha,
                request_id="M2-1E4B2301FADD",
                ftp_factory=factory,
            )
            self.assertTrue(result.uploaded_new)
            self.assertTrue(result.remote_sha256_verified)
            self.assertTrue(result.remote_retained)
            self.assertIn(result.remote_name, shared)

    def test_existing_identical_remote_is_reused(self):
        with tempfile.TemporaryDirectory() as tmp:
            artifact, sha = self.make_artifact(Path(tmp))
            remote_name = f"M2-1E4B2301FADD_{sha[:12]}.gcode.3mf"
            shared = {remote_name: artifact.read_bytes()}
            factory = lambda **kwargs: FakeFTP(files=shared)
            result = upload_audited_artifact(
                ip_address="192.168.1.5",
                access_code="secret",
                artifact_path=artifact,
                artifact_sha256=sha,
                request_id="M2-1E4B2301FADD",
                ftp_factory=factory,
            )
            self.assertFalse(result.uploaded_new)
            self.assertTrue(result.reused_existing_remote)
            self.assertTrue(result.remote_sha256_verified)

    def test_existing_wrong_size_is_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            artifact, sha = self.make_artifact(Path(tmp))
            remote_name = f"M2-1E4B2301FADD_{sha[:12]}.gcode.3mf"
            shared = {remote_name: b"wrong"}
            factory = lambda **kwargs: FakeFTP(files=shared)
            with self.assertRaises(Gate3V33Error):
                upload_audited_artifact(
                    ip_address="192.168.1.5",
                    access_code="secret",
                    artifact_path=artifact,
                    artifact_sha256=sha,
                    request_id="M2-1E4B2301FADD",
                    ftp_factory=factory,
                )

    def test_existing_same_size_wrong_hash_is_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            artifact, sha = self.make_artifact(Path(tmp))
            remote_name = f"M2-1E4B2301FADD_{sha[:12]}.gcode.3mf"
            original = artifact.read_bytes()
            wrong = bytes([original[0] ^ 1]) + original[1:]
            shared = {remote_name: wrong}
            factory = lambda **kwargs: FakeFTP(files=shared)
            with self.assertRaises(Gate3V33Error):
                upload_audited_artifact(
                    ip_address="192.168.1.5",
                    access_code="secret",
                    artifact_path=artifact,
                    artifact_sha256=sha,
                    request_id="M2-1E4B2301FADD",
                    ftp_factory=factory,
                )

    def test_empty_access_code_is_blocked(self):
        with tempfile.TemporaryDirectory() as tmp:
            artifact, sha = self.make_artifact(Path(tmp))
            with self.assertRaises(Gate3V33Error):
                upload_audited_artifact(
                    ip_address="192.168.1.5",
                    access_code="",
                    artifact_path=artifact,
                    artifact_sha256=sha,
                    request_id="M2-1E4B2301FADD",
                    ftp_factory=FakeFTP,
                )


class Gate3PipelineTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.request_id = "M2-1E4B2301FADD"
        self.device_id = "00M09A3A1700722"
        self.m4_task = self.root / "outputs" / "m4" / self.request_id
        self.m4_task.mkdir(parents=True)
        (self.m4_task / "m4_gate1_autodiscovered_device_v31.json").write_text(json.dumps({
            "request_id": self.request_id,
            "device_id": self.device_id,
            "ip_address": "192.168.1.5"
        }), encoding="utf-8")
        (self.m4_task / "m4_gate1_autodiscovery_probe_v31.json").write_text(json.dumps({
            "request_id": self.request_id,
            "status": "readonly_probe_passed",
            "all_attempts_passed": True,
            "attempt_count": 10,
            "device_id_autodiscovered": self.device_id
        }), encoding="utf-8")
        (self.m4_task / "m4_gate2_ftps_probe_v32.json").write_text(json.dumps({
            "request_id": self.request_id,
            "stage": "developer_mode_ftps_canary_probe_v32",
            "status": "ftps_probe_passed",
            "device_id": self.device_id,
            "all_attempts_passed": True,
            "attempt_count": 1,
            "success_count": 1,
            "transport_fix": {
                "implicit_ftps": True,
                "tls_session_reuse_on_data_channel": True,
                "remote_presence_check": "SIZE"
            }
        }), encoding="utf-8")
        m3_task = self.root / "outputs" / "m3" / self.request_id
        m3_task.mkdir(parents=True)
        self.artifact = m3_task / "controlled_slice_smoke.gcode.3mf"
        with zipfile.ZipFile(self.artifact, "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("Metadata/plate_1.gcode", "; generated by Bambu Studio\\nG1 X1 Y1\\n")
            archive.writestr("3D/3dmodel.model", "model")
        self.artifact_sha = hashlib.sha256(self.artifact.read_bytes()).hexdigest()
        (m3_task / "m3_gcode_audit.json").write_text(json.dumps({
            "schema_version": "0.1.0",
            "module": "M3",
            "phase": 5,
            "stage": "slice_and_gcode_audit",
            "request_id": self.request_id,
            "status": "audit_passed",
            "hard_constraints_passed": True,
            "hard_failure_count": 0,
            "artifact": {
                "path": str(self.artifact),
                "sha256": self.artifact_sha,
                "size_bytes": self.artifact.stat().st_size,
                "gcode_entries": ["Metadata/plate_1.gcode"]
            }
        }), encoding="utf-8")
        (m3_task / "m3_final_acceptance.json").write_text(json.dumps({
            "schema_version": "0.1.0",
            "module": "M3",
            "phase": 7,
            "stage": "final_acceptance",
            "request_id": self.request_id,
            "status": "m3_accepted",
            "m3_complete": True,
            "m4_activation_authorized": False,
            "hard_constraints_passed": True,
            "next_module": "M4"
        }), encoding="utf-8")
        (self.m4_task / "m4_gate2_ftps_tls_pin_v32.json").write_text(json.dumps({
            "ip_address": "192.168.1.5",
            "device_id": self.device_id,
            "certificate_sha256": "AA" * 32
        }), encoding="utf-8")

    def tearDown(self) -> None:
        self.temp.cleanup()

    def fake_upload(self, **kwargs):
        return UploadResult(
            remote_name=f"{self.request_id}_{self.artifact_sha[:12]}.gcode.3mf",
            remote_directory="/cache",
            uploaded_new=True,
            reused_existing_remote=False,
            remote_size_verified=True,
            remote_sha256_verified=True,
            remote_sha256=self.artifact_sha,
            remote_size_bytes=self.artifact.stat().st_size,
            remote_retained=True,
        )

    def test_pipeline_report_keeps_print_start_locked(self):
        with (
            patch("am_print_executor.audited_artifact_upload_v33.get_server_fingerprint", return_value="AA" * 32),
            patch("am_print_executor.audited_artifact_upload_v33.upload_audited_artifact", side_effect=self.fake_upload),
        ):
            result = run_gate3_v33(
                self.root,
                self.request_id,
                "SECRET",
                expected_authorization_phrase(self.request_id),
            )
        self.assertEqual(result["status"], "audited_artifact_uploaded")
        self.assertFalse(result["authorization"]["print_start_authorized"])
        self.assertEqual(result["policy"]["mqtt_publish_count"], 0)
        self.assertEqual(result["policy"]["print_start_command_count"], 0)
        self.assertTrue(result["artifact"]["remote_sha256_verified"])
        self.assertTrue(result["artifact"]["remote_retained"])

    def test_wrong_authorization_is_blocked_before_upload(self):
        with self.assertRaises(Gate3V33Error):
            run_gate3_v33(self.root, self.request_id, "SECRET", "NO")

    def test_failed_gate2_is_blocked(self):
        path = self.m4_task / "m4_gate2_ftps_probe_v32.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        data["status"] = "ftps_probe_failed"
        path.write_text(json.dumps(data), encoding="utf-8")
        with self.assertRaises(Gate3V33Error):
            run_gate3_v33(
                self.root,
                self.request_id,
                "SECRET",
                expected_authorization_phrase(self.request_id),
            )

    def test_modified_audited_artifact_is_blocked(self):
        self.artifact.write_bytes(self.artifact.read_bytes() + b"changed")
        with self.assertRaises(Gate3V33Error):
            run_gate3_v33(
                self.root,
                self.request_id,
                "SECRET",
                expected_authorization_phrase(self.request_id),
            )


if __name__ == "__main__":
    unittest.main()
